In [1]:
import torch
import numpy as np


# Critical

In [13]:
# Broadcasting

tensor_2d = torch.ones(4,1)
print(tensor_2d)
tensor_1d = torch.randn(3)
print(tensor_1d)
print()
tensor_broadcast_expanded = torch.add(tensor_2d, tensor_1d)
print(tensor_broadcast_expanded)
print(tensor_broadcast_expanded.shape)

# Note also
reverse_broadcast = torch.add(tensor_1d, tensor_2d)
torch.all(tensor_broadcast_expanded.eq(reverse_broadcast)) 

tensor([[1.],
        [1.],
        [1.],
        [1.]])
tensor([ 1.8398, -0.6919, -0.3470])

tensor([[2.8398, 0.3081, 0.6530],
        [2.8398, 0.3081, 0.6530],
        [2.8398, 0.3081, 0.6530],
        [2.8398, 0.3081, 0.6530]])
torch.Size([4, 3])


tensor(True)

In [29]:
# STARTS FROM THE RIGHT
# can line up trailing dimensions
x=torch.ones(3,2,2,2)
y=torch.ones(  1,1,2)
# becomes y=torch.ones(3,2,2,2)
xy = torch.add(x,y)
print(xy)

# x and y are broadcastable.
# 1st trailing dimension: both have size 1
# 2nd trailing dimension: y has size 1
# 3rd trailing dimension: x size == y size
# 4th trailing dimension: y dimension doesn't exist

# Note we have 3 pairs of 2x2s
xy.numel()

tensor([[[[2., 2.],
          [2., 2.]],

         [[2., 2.],
          [2., 2.]]],


        [[[2., 2.],
          [2., 2.]],

         [[2., 2.],
          [2., 2.]]],


        [[[2., 2.],
          [2., 2.]],

         [[2., 2.],
          [2., 2.]]]])


24

In [37]:
# squeeze a tensor: remove the 1s from the shape
d = torch.ones(2,1,2,1)
print(d); print()
print(d.squeeze()); print()
print(d.unsqueeze(dim=0))
#print(d.unsqueeze(dim=1))

tensor([[[[1.],
          [1.]]],


        [[[1.],
          [1.]]]])

tensor([[1., 1.],
        [1., 1.]])

tensor([[[[[1.],
           [1.]]],


         [[[1.],
           [1.]]]]])


In [39]:
# flatten a tensor: concat one dimension
c = torch.rand([3,3,4])
c.flatten()

tensor([0.7212, 0.0262, 0.8675, 0.6944, 0.4912, 0.0213, 0.3186, 0.0056, 0.8242,
        0.9966, 0.6115, 0.6244, 0.4733, 0.4002, 0.3353, 0.9631, 0.6802, 0.5433,
        0.2166, 0.6288, 0.9139, 0.7898, 0.0600, 0.9358, 0.9083, 0.1427, 0.2134,
        0.1975, 0.0659, 0.9850, 0.8953, 0.4289, 0.9908, 0.7020, 0.1698, 0.8634])

In [2]:
np.random.seed(42)
x = np.random.rand(100, 1)
y = 1 + 2 * x + .1 * np.random.randn(100, 1)

# Shuffles the indices
idx = np.arange(100)
np.random.shuffle(idx)

# Uses first 80 random indices for train
train_idx = idx[:80]
# Uses the remaining indices for validation
val_idx = idx[80:]

# Generates train and validation sets
x_train, y_train = x[train_idx], y[train_idx]
x_val, y_val = x[val_idx], y[val_idx]

# TORCH IT

x_train_tensor = torch.from_numpy(x_train).float()
y_train_tensor = torch.from_numpy(y_train).float()

a = torch.randn(1, requires_grad=True, dtype=torch.float)
b = torch.randn(1, requires_grad=True, dtype=torch.float)

yhat = a + b * x_train_tensor
error = y_train_tensor - yhat
loss = (error ** 2).mean()
loss

tensor(7.3426, grad_fn=<MeanBackward0>)